name: ntts_dart
description: Neural Text To Speech dart cross platform support server side and client side without request internet data and work on cpu.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ffi: ^2.0.1
  galaxeus_lib: ^0.0.63
  path: ^1.8.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  msix: ^3.9.1
  packagex: ^0.0.25
  play: ^0.0.25
  test: ^1.21.0

msix_config: 
  display_name: ntts_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.ntts_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: ntts_dart
  dart_target: ntts_dart
  flutter_target: main
  dart_name: ntts_dart
  flutter_name: ntts_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
