name: ntts_dart
description: Neural Text To Speech dart cross platform support server side and client side without request internet data and work on cpu.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ffi: ^2.0.2 
  general_lib: ^0.0.1
  path: ^1.8.3
  play: ^0.0.40 

dev_dependencies:
  lints: ^2.1.1
  msix: ^3.16.0
  packagex: ^0.0.31
  test: ^1.23.1

dependency_overrides:
  http: ^1.1.0
  
 

packagex:
  name: ntts_dart
  dart_target: ntts_dart
  flutter_target: main
  dart_name: ntts_dart
  flutter_name: ntts_dart
  is_without_platform_name: true
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  

msix_config: 
  display_name: ntts_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.ntts_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam
